import fs from 'fs'; import path from 'path'; import PDFDocument from 'pdfkit';
import { Agent,AgentExecution,CRMActivity,Email,Meeting,Invoice,Ticket,Notification,Memory } from './models.js';
import { config } from './config.js';
const words=(s)=>s.toLowerCase();
export function analyzeEmail(subject='',body='') { const text=words(subject+' '+body); const has=(a)=>a.some(w=>text.includes(w)); const negative=has(['angry','cancel','broken','refund','late','complaint','bad','issue','failed']); const positive=has(['thanks','great','love','happy','excellent','appreciate','renew']); const urgency=has(['urgent','asap','immediately'])?'critical':has(['deadline','soon','priority'])?'high':'medium'; const intent=has(['meeting','schedule','call'])?'schedule_meeting':has(['invoice','payment','receipt'])?'invoice_request':has(['support','broken','issue','failed','refund'])?'support_request':has(['demo','pricing','buy','proposal'])?'sales_opportunity':'general_inquiry'; return {sentiment:negative?'negative':positive?'positive':'neutral',intent,urgency,confidence:.85,autoResponse:'Thank you for contacting NxtBiz. Our operations team is reviewing your request.',recommendations:[intent==='support_request'?'Create a support ticket':'Add CRM follow-up',urgency==='critical'?'Escalate immediately':'Review within one business day']}; }
export async function notify(io, userId, type,title,message,metadata={}) { const notice=await Notification.create({userId,type,title,message,metadata}); io?.emit(type,notice); return notice; }
export async function orchestrate({email, userId, io}) { const context={emailId:email?._id,eventId:crypto.randomUUID(),intent:email?.intent,customerId:email?.customerId}; const planned=['intent-agent','task-planner-agent']; const map={schedule_meeting:'meeting-agent',invoice_request:'invoice-agent',support_request:'customer-support-agent',sales_opportunity:'email-agent'}; if(map[context.intent]) planned.push(map[context.intent]); planned.push('crm-agent','chief-of-staff-agent'); for(const agentId of planned){ const execution=await AgentExecution.create({agentId,eventId:context.eventId,status:'running',input:context,logs:['Started'],startedAt:new Date()}); const output={message:`${agentId} completed`,context}; if(agentId==='meeting-agent'&&email?.customerId) await Meeting.create({title:'Email follow-up meeting',customerId:email.customerId,startTime:new Date(Date.now()+86400000),attendees:[email.sender]}); if(agentId==='customer-support-agent'&&email?.customerId) await Ticket.create({customerId:email.customerId,priority:email.urgency==='critical'?'critical':'high',issue:email.subject}); if(agentId==='crm-agent'&&email?.customerId) await CRMActivity.create({customerId:email.customerId,type:'email',title:'AI email follow-up',body:`Intent: ${email.intent}`,createdBy:userId}); await Agent.updateOne({agentId},{$set:{status:'ready',lastExecution:new Date()}}); await AgentExecution.findByIdAndUpdate(execution._id,{status:'completed',output,logs:['Started','Completed'],finishedAt:new Date()}); } if(email) {email.processed=true;await email.save();} await notify(io,userId,'agent_completed','Agent orchestration completed','NxtBiz agents completed the operational follow-up.',context); return context; }
export function makePdf(kind, title, lines) { const dir=path.resolve('storage/pdfs'); fs.mkdirSync(dir,{recursive:true}); const filename=`${kind}-${Date.now()}.pdf`; const file=path.join(dir,filename); const pdf=new PDFDocument(); pdf.pipe(fs.createWriteStream(file)); pdf.fontSize(22).text('NxtBiz'); pdf.moveDown().fontSize(16).text(title); pdf.moveDown(); lines.forEach(([k,v])=>pdf.fontSize(11).text(`${k}: ${v}`)); pdf.end(); return `${config.pdfBaseUrl}/${filename}`; }
export function healthScore({customerSatisfaction=80,responseTime=75,invoiceCollection=75,ticketResolution=75,leadConversion=70,meetingMomentum=70}={}) { return {score:Math.round(customerSatisfaction*.28+responseTime*.16+invoiceCollection*.20+ticketResolution*.20+leadConversion*.16),factors:{customerSatisfaction,responseTime,invoiceCollection,leadConversion,ticketResolution,meetingMomentum}}; }
